
### エリアの値を取得する
GET {{protcol}}://{{host}}/get/area
    ?id=1
Content-Type: application/json
Accept: application/json


### エリアの値を取得する
GET {{protcol}}://{{host}}/get/area/all
Content-Type: application/json
Accept: application/json


### エリアの値を保存する
POST {{protcol}}://{{host}}/set/area
    ?name=sysken
Content-Type: application/json


